version: 2
jobs:
  build:
    working_directory: ~/applicaster/Hooks-RN
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
      CIRCLE_BUILD_IOS: /tmp/build/ios
      CIRCLE_BUILD_ANDROID: /tmp/build/android
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    - checkout
    
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS $CIRCLE_BUILD_IOS $CIRCLE_BUILD_ANDROID

    - run:
        name: Install node 8.1.4
        working_directory: ~/applicaster/Hooks-RN
        command: nvm install 8.1.4 && nvm alias default 8.1.4
    
    - run:
        name: Install npm
        working_directory: ~/applicaster/Hooks-RN
        command: npm i -g npm@5.4.2

    - run:
        name: Install react-native@0.50.4
        working_directory: ~/applicaster/Hooks-RN
        command: npm i -g react-native@0.50.4

    - run: 
        name: NPM install
        command: npm install

    - deploy:
        name: S3 Bundle deployment
        command: bash .circleci/deploy.sh ${CIRCLE_BRANCH}
