version: 2
jobs:
  build:
    working_directory: ~/applicaster/Feed-RN
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
    - image: circleci/build-image:ubuntu-14.04-XXL-upstart-1189-5614f37
      command: /sbin/init
    steps:
    - checkout
    - run:
        name: Install node 8.1.4
        working_directory: ~/applicaster/Feed-RN
        command: nvm install 8.1.4 && nvm alias default 8.1.4
    
    - run:
        name: Install npm
        working_directory: ~/applicaster/Feed-RN
        command: npm i -g npm@5.4.2

    - run:
        name: Install react-native@0.50.4
        working_directory: ~/applicaster/Feed-RN
        command: npm i -g react-native@0.50.4

    - run: 
        name: NPM install
        command: npm install
    
    - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
    - run: mkdir -p $CIRCLE_TEST_REPORTS/junit
    - run:
        name: Mocha Unit Tests
        command: npm run test-reporter
    - run: cp test-results.xml $CIRCLE_TEST_REPORTS/junit

    - run:
        name: Jest Unit Tests
        command: npm run jest

    - store_test_results:
        path: /tmp/circleci-test-results
    - store_artifacts:
        path: /tmp/circleci-artifacts
    - store_artifacts:
        path: /tmp/circleci-test-results

    - deploy:
      name: S3 Bundle deployment
      command: bash .circleci/deploy.sh ${CIRCLE_BRANCH}
